version: '2.1'
services:
  zookeeper:
    image: 10.10.10.160:8010/maxleap/zookeeper:3.4.8
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    hostname: kafka
    links:
      - zookeeper
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
    healthcheck:
      test: "sleep 15 && exit 0;"
      interval: 30s
      timeout: 30s
      retries: 1
  build:
    command: sh -c 'mvn clean test' #mvn --help
    image: maven:3-jdk-8-alpine
    links:
      - zookeeper
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - '.:/code'
      - '~/.m2/repository:/root/.m2/repository'
    working_dir: /code

# docker-compose run --rm build sh -c 'mvn clean test' && docker-compose stop && docker-compose rm -f
